export enum LOCATION_TYPE {
  AID_ROOM = "AIDROOM",
  HUT = "HUT",
  LODGE = "LODGE",
  LIFT = "LIFT",
  TRAIL = "TRAIL",
  MOUNTAIN = "MOUNTAIN",
  OTHER = "OTHER",
}

export enum STATUS {
  OPEN = "OPEN",
  CLOSED = "CLOSED",
  ON_HOLD = "ON_HOLD",
  UNKNOWN = "UNKNOWN",
}

export enum INCIDENT_STATUS {
  STANDBY = "STANDBY",
  REPORTED = "REPORTED",
  IN_PROGRESS = "IN_PROGRESS",
  RESOLVED = "RESOLVED",
  UNKNOWN = "UNKNOWN",
}

export enum EQUIPMENT_STATUS {
  OPERATIONAL = "OPERATIONAL",
  IN_SERVICE = "IN_SERVICE",
  OUT_OF_SERVICE = "OUT_OF_SERVICE",
  IN_USE = "IN_USE",
  CLEANING = "CLEANING",
  NEEDS_INSPECTION = "NEEDS_INSPECTION",
  PENDING_REPAIR = "PENDING_REPAIR",
  UNDER_MAINTENANCE = "UNDER_MAINTENANCE",
  LOST = "LOST",
  DAMAGED = "DAMAGED",
  RETIRED = "RETIRED",
  STANDBY = "STANDBY",
}

export enum LIFT_TYPE {
  CHAIR = "CHAIR",
  GONDOLA = "GONDOLA",
  T_BAR = "T_BAR",
  ROPE_TOW = "ROPE_TOW",
  MAGIC_CARPET = "MAGIC_CARPET",
  
  OTHER = "OTHER",
}

export enum TRAIL_CONDITION {
  MACHINE_GROOMED = "MACHINE_GROOMED",
  HARD_PACK = "HARD_PACK",
  PACKED_POWDER = "PACKED_POWDER",
  POWDER = "POWDER",
  MOGULS = "MOGULS",
  NATURAL = "NATURAL",
  GLADES = "GLADES",
  CLOSED = "CLOSED",
}

export enum TRAIL_DIFFICULTY {
  GREEN_CIRCLE = "GREEN_CIRCLE",
  BLUE_SQUARE = "BLUE_SQUARE",
  BLACK_DIAMOND = "BLACK_DIAMOND",
  DOUBLE_BLACK_DIAMOND = "DOUBLE_BLACK_DIAMOND",
  TERRAIN_PARK = "TERRAIN_PARK",
  RACE_COURSE = "RACE_COURSE",
  OTHER = "OTHER",
}

export enum DEPARTMENT {
  PATROL = "PATROL",
  LIFT_OPERATIONS = "LIFT_OPERATIONS",
  DISPATCH = "DISPATCH",
  MAINTENANCE = "MAINTENANCE",
  ADMINISTRATION = "ADMINISTRATION",
  OTHER = "OTHER",
}

export enum AREA_TYPE {
  BASE_AREA = "BASE_AREA",
  MOUNTAIN_AREA = "MOUNTAIN_AREA",
  SUMMIT = "SUMMIT",
  OTHER = "OTHER",
}

export enum EMPLOYEE_ROLES {
  SUPERVISOR = "SUPERVISOR",
  ADVANCED_PATROLLER = "ADVANCED_PATROLLER",
  HILL_CHIEF = "HILL_CHIEF",
  SPECIALIST = "SPECIALIST",
  TRAINER = "TRAINER",
  DIRECTOR = "DIRECTOR",
}